dist: trusty

language: php

php:
  - 7.4

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - dev
    - master

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost latest

script:
  - composer test
